version: 2

updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: daily
      time: 08:00

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
      time: 08:00
