version: '3'

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017

  redis:
    image: redis
    ports:
      - 6379:6379

  docker:
    image: docker:dind
    ports:
      - 2375:2375
    privileged: true
    command: dockerd --host=tcp://0.0.0.0:2375 --tls=false
