name: Build

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      OTEL_TRACES_SAMPLER: parentbased_always_on
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Boot services
        run: docker-compose up -d

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Run unit tests
        run: python -m unittest discover -vb tests/unit/

      - name: Run integration tests
        run: python -m unittest discover -vb tests/integration/
